language: ruby
script: rake test
branches:
  only:
    - master
services:
  - redis-server
rvm:
  - 2.0.0
  - 2.1.5
  - 2.3.0
  - ruby-head
  - jruby-19mode
  - jruby-head
jdk:
  - oraclejdk8
  - openjdk8
matrix:
  exclude:
    - rvm: 2.3.0
      jdk: openjdk8
    - rvm: 2.1.1
      jdk: openjdk8
    - rvm: 2.0.0
      jdk: openjdk8
    - rvm: ruby-head
      jdk: openjdk8
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-19mode
